# Default config

server:
  port: 3030

# `appData` is a hash of values that will be set on the `req.rendrApp` (middleware)
# and `this.app` (models, views, controllers). These are available in both the
# client and the server.
appData:
  someProperty: someValue

db:
  host: localhost
  name: mydb
  options:
    server:
      auto_reconnect: true
      socketOptions:
        keepAlive: 1

session:
  secret: 1-9-6-306yoyogishibuyakutokyojapan
